### ISSUE TITLE
Add support for popup attribute

### ISSUE THREAD

**Issue by giswqs** [jtmiclat/folium-pmtiles#11]
It would be great to add support for popup attribute, just like the [PMTiles Viewer](https://protomaps.github.io/PMTiles/). 

![Screenshot_20231105_151155](https://github.com/jtmiclat/folium-pmtiles/assets/5016453/d4e842bd-9b04-4ad1-a170-7c3a02840b36)

**Comment by jtmiclat** [comment]
Hi! This would be super useful but requires a bit of Javascript.

This will most likely not be possible with the protomaps-leaflet but would be possible with maplibre implementation and not have have that much customization

**Comment by giswqs** [comment]
It would be great to have the maplibre implementation. This is a very useful feature.

**Comment by jtmiclat** [comment]
@giswqs I published 0.4.0 which adds `PMTilesMapLibreTooltip`

Example usage can be found

https://github.com/jtmiclat/folium-pmtiles/blob/master/example/pmtiles_vector_maplibre.ipynb 

Let me know if this works for you!

**Comment by giswqs** [comment]
Awesome! I will try it out shortly. Thank you.

**Comment by giswqs** [comment]
Nice! I can confirm that it works properly.
![image](https://github.com/jtmiclat/folium-pmtiles/assets/5016453/cdcb0104-0e0d-45d2-9311-90844906c04c)

**Comment by giswqs** [comment]
https://github.com/jtmiclat/folium-pmtiles/issues/11
